INSERT INTO roles (role_code, role_name) VALUES 
	('R01', 'Super Admin'),
	('R02', 'Member'),
	('R03', 'Premium');
		
INSERT INTO users (id, role_id, email, "password") VALUES
	('1', (SELECT id FROM roles WHERE role_code = 'R01'), 'admin@mail.com', 'admin');

INSERT INTO industry (industry_code, industry_name, created_by) VALUES
	('IDT01', 'Accounting', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('IDT02', 'Retail', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('IDT03', 'Information Technology and Service', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('IDT04', 'Financial Services', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('IDT05', 'Logistic and Supply Chain', (SELECT id FROM users WHERE email = 'admin@mail.com'));
	
INSERT INTO position (position_code, position_name, created_by) VALUES
	('POS01', 'Programmer', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('POS02', 'Business Development', (SELECT id FROM users WHERE email = 'admin@mail.com'));
			
INSERT INTO activity_type (activity_type_code, activity_type_name, price, created_by) VALUES
	('AT01', 'Event', 100000, (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('AT02', 'Course', 50000, (SELECT id FROM users WHERE email = 'admin@mail.com'));

INSERT INTO thread_type (thread_type_code, thread_type_name, created_by) VALUES
	('THT01', 'Regular', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('THT02', 'Polling', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('THT03', 'Premium', (SELECT id FROM users WHERE email = 'admin@mail.com'));

INSERT INTO transaction_status (status_code, status_name, created_by) VALUES
	('ST01', 'Pending', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('ST02', 'Approved', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('ST03', 'Rejected', (SELECT id FROM users WHERE email = 'admin@mail.com'));

INSERT INTO subscribe(duration, price, created_by) VALUES
	(1, 25000, (SELECT id FROM users WHERE email = 'admin@mail.com')),
	(3, 50000, (SELECT id FROM users WHERE email = 'admin@mail.com')),
	(6, 100000, (SELECT id FROM users WHERE email = 'admin@mail.com'));

INSERT INTO province (province_code, province_name, created_by) VALUES
	('11',	'ACEH', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('12',	'SUMATERA UTARA', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('13',	'SUMATERA BARAT', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('14',	'RIAU', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('15',	'JAMBI', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('16',	'SUMATERA SELATAN', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('17',	'BENGKULU', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('18',	'LAMPUNG', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('19',	'KEPULAUAN BANGKA BELITUNG', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('21',	'KEPULAUAN RIAU', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('31',	'DKI JAKARTA', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('32',	'JAWA BARAT', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('33',	'JAWA TENGAH', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('34',	'DAERAH ISTIMEWA YOGYAKARTA', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('35',	'JAWA TIMUR', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('36',	'BANTEN', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('51',	'BALI', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('52',	'NUSA TENGGARA BARAT', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('53',	'NUSA TENGGARA TIMUR', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('61',	'KALIMANTAN BARAT', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('62',	'KALIMANTAN TENGAH', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('63',	'KALIMANTAN SELATAN', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('64',	'KALIMANTAN TIMUR', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('65',	'KALIMANTAN UTARA', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('71',	'SULAWESI UTARA', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('72',	'SULAWESI TENGAH', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('73',	'SULAWESI SELATAN', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('74',	'SULAWESI TENGGARA', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('75',	'GORONTALO', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('76',	'SULAWESI BARAT', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('81',	'MALUKU', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('82',	'MALUKU UTARA', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('91',	'PAPUA', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('92',	'PAPUA BARAT', (SELECT id FROM users WHERE email = 'admin@mail.com'));
			
INSERT INTO city (city_code, province_id, city_name, created_by) VALUES
('1101',	(SELECT id FROM province WHERE province_code = '11'),	'KAB. ACEH SELATAN', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1102',	(SELECT id FROM province WHERE province_code = '11'),	'KAB. ACEH TENGGARA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1103',	(SELECT id FROM province WHERE province_code = '11'),	'KAB. ACEH TIMUR', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1104',	(SELECT id FROM province WHERE province_code = '11'),	'KAB. ACEH TENGAH', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1105',	(SELECT id FROM province WHERE province_code = '11'),	'KAB. ACEH BARAT', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1106',	(SELECT id FROM province WHERE province_code = '11'),	'KAB. ACEH BESAR', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1107',	(SELECT id FROM province WHERE province_code = '11'),	'KAB. PIDIE', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1108',	(SELECT id FROM province WHERE province_code = '11'),	'KAB. ACEH UTARA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1109',	(SELECT id FROM province WHERE province_code = '11'),	'KAB. SIMEULUE', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1110',	(SELECT id FROM province WHERE province_code = '11'),	'KAB. ACEH SINGKIL', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1111',	(SELECT id FROM province WHERE province_code = '11'),	'KAB. BIREUEN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1112',	(SELECT id FROM province WHERE province_code = '11'),	'KAB. ACEH BARAT DAYA', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1113',	(SELECT id FROM province WHERE province_code = '11'),	'KAB. GAYO LUES', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1114',	(SELECT id FROM province WHERE province_code = '11'),	'KAB. ACEH JAYA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1115',	(SELECT id FROM province WHERE province_code = '11'),	'KAB. NAGAN RAYA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1116',	(SELECT id FROM province WHERE province_code = '11'),	'KAB. ACEH TAMIANG', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1117',	(SELECT id FROM province WHERE province_code = '11'),	'KAB. BENER MERIAH', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1118',	(SELECT id FROM province WHERE province_code = '11'),	'KAB. PIDIE JAYA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1171',	(SELECT id FROM province WHERE province_code = '11'),	'KOTA BANDA ACEH', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1172',	(SELECT id FROM province WHERE province_code = '11'),	'KOTA SABANG', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1173',	(SELECT id FROM province WHERE province_code = '11'),	'KOTA LHOKSEUMAWE', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1174',	(SELECT id FROM province WHERE province_code = '11'),	'KOTA LANGSA', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1175',	(SELECT id FROM province WHERE province_code = '11'),	'KOTA SUBULUSSALAM', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1201',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. TAPANULI TENGAH', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1202',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. TAPANULI UTARA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1203',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. TAPANULI SELATAN',			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1204',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. NIAS', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1205',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. LANGKAT', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1206',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. KARO', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1207',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. DELI SERDANG', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1208',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. SIMALUNGUN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1209',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. ASAHAN', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1210',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. LABUHANBATU', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1211',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. DAIRI', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1212',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. TOBA SAMOSIR', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1213',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. MANDAILING NATAL',			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1214',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. NIAS SELATAN', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1215',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. PAKPAK BHARAT', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1216',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. HUMBANG HASUNDUTAN', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1217',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. SAMOSIR', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1218',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. SERDANG BEDAGAI', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1219',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. BATU BARA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1220',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. PADANG LAWAS UTARA', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1221',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. PADANG LAWAS', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1222',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. LABUHANBATU SELATAN', 		(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1223',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. LABUHANBATU UTARA', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1224',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. NIAS UTARA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1225',	(SELECT id FROM province WHERE province_code = '12'),	'KAB. NIAS BARAT', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1271',	(SELECT id FROM province WHERE province_code = '12'),	'KOTA MEDAN', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1272',	(SELECT id FROM province WHERE province_code = '12'),	'KOTA PEMATANGSIANTAR', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1273',	(SELECT id FROM province WHERE province_code = '12'),	'KOTA SIBOLGA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1274',	(SELECT id FROM province WHERE province_code = '12'),	'KOTA TANJUNG BALAI', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1275',	(SELECT id FROM province WHERE province_code = '12'),	'KOTA BINJAI', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1276',	(SELECT id FROM province WHERE province_code = '12'),	'KOTA TEBING TINGGI', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1277',	(SELECT id FROM province WHERE province_code = '12'),	'KOTA PADANG SIDEMPUAN', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1278',	(SELECT id FROM province WHERE province_code = '12'),	'KOTA GUNUNGSITOLI', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1301',	(SELECT id FROM province WHERE province_code = '13'),	'KAB. PESISIR SELATAN', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1302',	(SELECT id FROM province WHERE province_code = '13'),	'KAB. SOLOK', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1303',	(SELECT id FROM province WHERE province_code = '13'),	'KAB. SIJUNJUNG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1304',	(SELECT id FROM province WHERE province_code = '13'),	'KAB. TANAH DATAR', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1305',	(SELECT id FROM province WHERE province_code = '13'),	'KAB. PADANG PARIAMAN', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1306',	(SELECT id FROM province WHERE province_code = '13'),	'KAB. AGAM', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1307',	(SELECT id FROM province WHERE province_code = '13'),	'KAB. LIMA PULUH KOTA', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1308',	(SELECT id FROM province WHERE province_code = '13'),	'KAB. PASAMAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1309',	(SELECT id FROM province WHERE province_code = '13'),	'KAB. KEPULAUAN MENTAWAI', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1310',	(SELECT id FROM province WHERE province_code = '13'),	'KAB. DHARMASRAYA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1311',	(SELECT id FROM province WHERE province_code = '13'),	'KAB. SOLOK SELATAN', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1312',	(SELECT id FROM province WHERE province_code = '13'),	'KAB. PASAMAN BARAT', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1371',	(SELECT id FROM province WHERE province_code = '13'),	'KOTA PADANG', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1372',	(SELECT id FROM province WHERE province_code = '13'),	'KOTA SOLOK', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1373',	(SELECT id FROM province WHERE province_code = '13'),	'KOTA SAWAHLUNTO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1374',	(SELECT id FROM province WHERE province_code = '13'),	'KOTA PADANG PANJANG', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1375',	(SELECT id FROM province WHERE province_code = '13'),	'KOTA BUKITTINGGI', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1376',	(SELECT id FROM province WHERE province_code = '13'),	'KOTA PAYAKUMBUH', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1377',	(SELECT id FROM province WHERE province_code = '13'),	'KOTA PARIAMAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1401',	(SELECT id FROM province WHERE province_code = '14'),	'KAB. KAMPAR', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1402',	(SELECT id FROM province WHERE province_code = '14'),	'KAB. INDRAGIRI HULU', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1403',	(SELECT id FROM province WHERE province_code = '14'),	'KAB. BENGKALIS', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1404',	(SELECT id FROM province WHERE province_code = '14'),	'KAB. INDRAGIRI HILIR', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1405',	(SELECT id FROM province WHERE province_code = '14'),	'KAB. PELALAWAN',					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1406',	(SELECT id FROM province WHERE province_code = '14'),	'KAB. ROKAN HULU', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1407',	(SELECT id FROM province WHERE province_code = '14'),	'KAB. ROKAN HILIR', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1408',	(SELECT id FROM province WHERE province_code = '14'),	'KAB. SIAK', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1409',	(SELECT id FROM province WHERE province_code = '14'),	'KAB. KUANTAN SINGINGI', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1410',	(SELECT id FROM province WHERE province_code = '14'),	'KAB. KEPULAUAN MERANTI', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1471',	(SELECT id FROM province WHERE province_code = '14'),	'KOTA PEKANBARU', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1472',	(SELECT id FROM province WHERE province_code = '14'),	'KOTA DUMAI', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1501',	(SELECT id FROM province WHERE province_code = '15'),	'KAB. KERINCI', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1502',	(SELECT id FROM province WHERE province_code = '15'),	'KAB. MERANGIN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1503',	(SELECT id FROM province WHERE province_code = '15'),	'KAB. SAROLANGUN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1504',	(SELECT id FROM province WHERE province_code = '15'),	'KAB. BATANGHARI', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1505',	(SELECT id FROM province WHERE province_code = '15'),	'KAB. MUARO JAMBI', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1506',	(SELECT id FROM province WHERE province_code = '15'),	'KAB. TANJUNG JABUNG BARAT',		(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1507',	(SELECT id FROM province WHERE province_code = '15'),	'KAB. TANJUNG JABUNG TIMUR',		(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1508',	(SELECT id FROM province WHERE province_code = '15'),	'KAB. BUNGO', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1509',	(SELECT id FROM province WHERE province_code = '15'),	'KAB. TEBO', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1571',	(SELECT id FROM province WHERE province_code = '15'),	'KOTA JAMBI',			 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1572',	(SELECT id FROM province WHERE province_code = '15'),	'KOTA SUNGAI PENUH', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1601',	(SELECT id FROM province WHERE province_code = '16'),	'KAB. OGAN KOMERING ULU', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1602',	(SELECT id FROM province WHERE province_code = '16'),	'KAB. OGAN KOMERING ILIR', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1603',	(SELECT id FROM province WHERE province_code = '16'),	'KAB. MUARA ENIM', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1604',	(SELECT id FROM province WHERE province_code = '16'),	'KAB. LAHAT', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1605',	(SELECT id FROM province WHERE province_code = '16'),	'KAB. MUSI RAWAS', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1606',	(SELECT id FROM province WHERE province_code = '16'),	'KAB. MUSI BANYUASIN', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1607',	(SELECT id FROM province WHERE province_code = '16'),	'KAB. BANYUASIN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1608',	(SELECT id FROM province WHERE province_code = '16'),	'KAB. OGAN KOMERING ULU TIMUR', 	(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1609',	(SELECT id FROM province WHERE province_code = '16'),	'KAB. OGAN KOMERING ULU SELATAN', 	(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1610',	(SELECT id FROM province WHERE province_code = '16'),	'KAB. OGAN ILIR', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1611',	(SELECT id FROM province WHERE province_code = '16'),	'KAB. EMPAT LAWANG', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1612',	(SELECT id FROM province WHERE province_code = '16'),	'KAB. PENUKAL ABAB LEMATANG ILIR',	(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1613',	(SELECT id FROM province WHERE province_code = '16'),	'KAB. MUSI RAWAS UTARA', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1671',	(SELECT id FROM province WHERE province_code = '16'),	'KOTA PALEMBANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1672',	(SELECT id FROM province WHERE province_code = '16'),	'KOTA PAGAR ALAM',					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1673',	(SELECT id FROM province WHERE province_code = '16'),	'KOTA LUBUK LINGGAU', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1674',	(SELECT id FROM province WHERE province_code = '16'),	'KOTA PRABUMULIH', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1701',	(SELECT id FROM province WHERE province_code = '17'),	'KAB. BENGKULU SELATAN', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1702',	(SELECT id FROM province WHERE province_code = '17'),	'KAB. REJANG LEBONG', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1703',	(SELECT id FROM province WHERE province_code = '17'),	'KAB. BENGKULU UTARA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1704',	(SELECT id FROM province WHERE province_code = '17'),	'KAB. KAUR', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1705',	(SELECT id FROM province WHERE province_code = '17'),	'KAB. SELUMA', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1706',	(SELECT id FROM province WHERE province_code = '17'),	'KAB. MUKO MUKO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1707',	(SELECT id FROM province WHERE province_code = '17'),	'KAB. LEBONG', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1708',	(SELECT id FROM province WHERE province_code = '17'),	'KAB. KEPAHIANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1709',	(SELECT id FROM province WHERE province_code = '17'),	'KAB. BENGKULU TENGAH', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1771',	(SELECT id FROM province WHERE province_code = '17'),	'KOTA BENGKULU', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1801',	(SELECT id FROM province WHERE province_code = '18'),	'KAB. LAMPUNG SELATAN', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1802',	(SELECT id FROM province WHERE province_code = '18'),	'KAB. LAMPUNG TENGAH', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1803',	(SELECT id FROM province WHERE province_code = '18'),	'KAB. LAMPUNG UTARA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1804',	(SELECT id FROM province WHERE province_code = '18'),	'KAB. LAMPUNG BARAT', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1805',	(SELECT id FROM province WHERE province_code = '18'),	'KAB. TULANG BAWANG', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1806',	(SELECT id FROM province WHERE province_code = '18'),	'KAB. TANGGAMUS', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1807',	(SELECT id FROM province WHERE province_code = '18'),	'KAB. LAMPUNG TIMUR', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1808',	(SELECT id FROM province WHERE province_code = '18'),	'KAB. WAY KANAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1809',	(SELECT id FROM province WHERE province_code = '18'),	'KAB. PESAWARAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1810',	(SELECT id FROM province WHERE province_code = '18'),	'KAB. PRINGSEWU', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1811',	(SELECT id FROM province WHERE province_code = '18'),	'KAB. MESUJI', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1812',	(SELECT id FROM province WHERE province_code = '18'),	'KAB. TULANG BAWANG BARAT', 		(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1813',	(SELECT id FROM province WHERE province_code = '18'),	'KAB. PESISIR BARAT', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1871',	(SELECT id FROM province WHERE province_code = '18'),	'KOTA BANDAR LAMPUNG', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1872',	(SELECT id FROM province WHERE province_code = '18'),	'KOTA METRO', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1901',	(SELECT id FROM province WHERE province_code = '19'),	'KAB. BANGKA', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1902',	(SELECT id FROM province WHERE province_code = '19'),	'KAB. BELITUNG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1903',	(SELECT id FROM province WHERE province_code = '19'),	'KAB. BANGKA SELATAN', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1904',	(SELECT id FROM province WHERE province_code = '19'),	'KAB. BANGKA TENGAH', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1905',	(SELECT id FROM province WHERE province_code = '19'),	'KAB. BANGKA BARAT', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1906',	(SELECT id FROM province WHERE province_code = '19'),	'KAB. BELITUNG TIMUR', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('1971',	(SELECT id FROM province WHERE province_code = '19'),	'KOTA PANGKAL PINANG', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('2101',	(SELECT id FROM province WHERE province_code = '21'),	'KAB. BINTAN', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('2102',	(SELECT id FROM province WHERE province_code = '21'),	'KAB. KARIMUN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('2103',	(SELECT id FROM province WHERE province_code = '21'),	'KAB. NATUNA', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('2104',	(SELECT id FROM province WHERE province_code = '21'),	'KAB. LINGGA', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('2105',	(SELECT id FROM province WHERE province_code = '21'),	'KAB. KEPULAUAN ANAMBAS', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('2171',	(SELECT id FROM province WHERE province_code = '21'),	'KOTA BATAM',	 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('2172',	(SELECT id FROM province WHERE province_code = '21'),	'KOTA TANJUNG PINANG', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3101',	(SELECT id FROM province WHERE province_code = '31'),	'KAB. ADM. KEP. SERIBU', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3171',	(SELECT id FROM province WHERE province_code = '31'),	'KOTA ADM. JAKARTA PUSAT', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3172',	(SELECT id FROM province WHERE province_code = '31'),	'KOTA ADM. JAKARTA UTARA', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3173',	(SELECT id FROM province WHERE province_code = '31'),	'KOTA ADM. JAKARTA BARAT', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3174',	(SELECT id FROM province WHERE province_code = '31'),	'KOTA ADM. JAKARTA SELATAN', 		(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3175',	(SELECT id FROM province WHERE province_code = '31'),	'KOTA ADM. JAKARTA TIMUR', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3201',	(SELECT id FROM province WHERE province_code = '32'),	'KAB. BOGOR', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3202',	(SELECT id FROM province WHERE province_code = '32'),	'KAB. SUKABUMI', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3203',	(SELECT id FROM province WHERE province_code = '32'),	'KAB. CIANJUR', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3204',	(SELECT id FROM province WHERE province_code = '32'),	'KAB. BANDUNG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3205',	(SELECT id FROM province WHERE province_code = '32'),	'KAB. GARUT', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3206',	(SELECT id FROM province WHERE province_code = '32'),	'KAB. TASIKMALAYA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3207',	(SELECT id FROM province WHERE province_code = '32'),	'KAB. CIAMIS', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3208',	(SELECT id FROM province WHERE province_code = '32'),	'KAB. KUNINGAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3209',	(SELECT id FROM province WHERE province_code = '32'),	'KAB. CIREBON', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3210',	(SELECT id FROM province WHERE province_code = '32'),	'KAB. MAJALENGKA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3211',	(SELECT id FROM province WHERE province_code = '32'),	'KAB. SUMEDANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3212',	(SELECT id FROM province WHERE province_code = '32'),	'KAB. INDRAMAYU', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3213',	(SELECT id FROM province WHERE province_code = '32'),	'KAB. SUBANG', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3214',	(SELECT id FROM province WHERE province_code = '32'),	'KAB. PURWAKARTA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3215',	(SELECT id FROM province WHERE province_code = '32'),	'KAB. KARAWANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3216',	(SELECT id FROM province WHERE province_code = '32'),	'KAB. BEKASI', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3217',	(SELECT id FROM province WHERE province_code = '32'),	'KAB. BANDUNG BARAT', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3218',	(SELECT id FROM province WHERE province_code = '32'),	'KAB. PANGANDARAN', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3271',	(SELECT id FROM province WHERE province_code = '32'),	'KOTA BOGOR', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3272',	(SELECT id FROM province WHERE province_code = '32'),	'KOTA SUKABUMI', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3273',	(SELECT id FROM province WHERE province_code = '32'),	'KOTA BANDUNG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3274',	(SELECT id FROM province WHERE province_code = '32'),	'KOTA CIREBON', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3275',	(SELECT id FROM province WHERE province_code = '32'),	'KOTA BEKASI', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3276',	(SELECT id FROM province WHERE province_code = '32'),	'KOTA DEPOK', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3277',	(SELECT id FROM province WHERE province_code = '32'),	'KOTA CIMAHI', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3278',	(SELECT id FROM province WHERE province_code = '32'),	'KOTA TASIKMALAYA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3279',	(SELECT id FROM province WHERE province_code = '32'),	'KOTA BANJAR', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3301',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. CILACAP', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3302',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. BANYUMAS', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3303',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. PURBALINGGA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3304',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. BANJARNEGARA',				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3305',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. KEBUMEN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3306',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. PURWOREJO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3307',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. WONOSOBO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3308',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. MAGELANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3309',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. BOYOLALI', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3310',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. KLATEN', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3311',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. SUKOHARJO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3312',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. WONOGIRI', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3313',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. KARANGANYAR', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3314',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. SRAGEN', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3315',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. GROBOGAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3316',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. BLORA', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3317',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. REMBANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3318',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. PATI', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3319',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. KUDUS', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3320',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. JEPARA', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3321',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. DEMAK', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3322',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. SEMARANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3323',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. TEMANGGUNG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3324',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. KENDAL', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3325',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. BATANG', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3326',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. PEKALONGAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3327',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. PEMALANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3328',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. TEGAL', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3329',	(SELECT id FROM province WHERE province_code = '33'),	'KAB. BREBES', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3371',	(SELECT id FROM province WHERE province_code = '33'),	'KOTA MAGELANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3372',	(SELECT id FROM province WHERE province_code = '33'),	'KOTA SURAKARTA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3373',	(SELECT id FROM province WHERE province_code = '33'),	'KOTA SALATIGA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3374',	(SELECT id FROM province WHERE province_code = '33'),	'KOTA SEMARANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3375',	(SELECT id FROM province WHERE province_code = '33'),	'KOTA PEKALONGAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3376',	(SELECT id FROM province WHERE province_code = '33'),	'KOTA TEGAL', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3401',	(SELECT id FROM province WHERE province_code = '34'),	'KAB. KULON PROGO', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3402',	(SELECT id FROM province WHERE province_code = '34'),	'KAB. BANTUL', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3403',	(SELECT id FROM province WHERE province_code = '34'),	'KAB. GUNUNGKIDUL', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3404',	(SELECT id FROM province WHERE province_code = '34'),	'KAB. SLEMAN', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3471',	(SELECT id FROM province WHERE province_code = '34'),	'KOTA YOGYAKARTA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3501',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. PACITAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3502',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. PONOROGO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3503',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. TRENGGALEK', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3504',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. TULUNGAGUNG', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3505',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. BLITAR', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3506',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. KEDIRI', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3507',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. MALANG', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3508',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. LUMAJANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3509',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. JEMBER', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3510',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. BANYUWANGI', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3511',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. BONDOWOSO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3512',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. SITUBONDO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3513',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. PROBOLINGGO', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3514',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. PASURUAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3515',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. SIDOARJO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3516',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. MOJOKERTO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3517',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. JOMBANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3518',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. NGANJUK', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3519',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. MADIUN', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3520',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. MAGETAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3521',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. NGAWI', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3522',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. BOJONEGORO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3523',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. TUBAN', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3524',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. LAMONGAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3525',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. GRESIK', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3526',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. BANGKALAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3527',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. SAMPANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3528',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. PAMEKASAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3529',	(SELECT id FROM province WHERE province_code = '35'),	'KAB. SUMENEP', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3571',	(SELECT id FROM province WHERE province_code = '35'),	'KOTA KEDIRI', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3572',	(SELECT id FROM province WHERE province_code = '35'),	'KOTA BLITAR', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3573',	(SELECT id FROM province WHERE province_code = '35'),	'KOTA MALANG', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3574',	(SELECT id FROM province WHERE province_code = '35'),	'KOTA PROBOLINGGO', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3575',	(SELECT id FROM province WHERE province_code = '35'),	'KOTA PASURUAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3576',	(SELECT id FROM province WHERE province_code = '35'),	'KOTA MOJOKERTO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3577',	(SELECT id FROM province WHERE province_code = '35'),	'KOTA MADIUN', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3578',	(SELECT id FROM province WHERE province_code = '35'),	'KOTA SURABAYA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3579',	(SELECT id FROM province WHERE province_code = '35'),	'KOTA BATU', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3601',	(SELECT id FROM province WHERE province_code = '36'),	'KAB. PANDEGLANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3602',	(SELECT id FROM province WHERE province_code = '36'),	'KAB. LEBAK', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3603',	(SELECT id FROM province WHERE province_code = '36'),	'KAB. TANGERANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3604',	(SELECT id FROM province WHERE province_code = '36'),	'KAB. SERANG', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3671',	(SELECT id FROM province WHERE province_code = '36'),	'KOTA TANGERANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3672',	(SELECT id FROM province WHERE province_code = '36'),	'KOTA CILEGON', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3673',	(SELECT id FROM province WHERE province_code = '36'),	'KOTA SERANG', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('3674',	(SELECT id FROM province WHERE province_code = '36'),	'KOTA TANGERANG SELATAN', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5101',	(SELECT id FROM province WHERE province_code = '51'),	'KAB. JEMBRANA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5102',	(SELECT id FROM province WHERE province_code = '51'),	'KAB. TABANAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5103',	(SELECT id FROM province WHERE province_code = '51'),	'KAB. BADUNG', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5104',	(SELECT id FROM province WHERE province_code = '51'),	'KAB. GIANYAR', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5105',	(SELECT id FROM province WHERE province_code = '51'),	'KAB. KLUNGKUNG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5106',	(SELECT id FROM province WHERE province_code = '51'),	'KAB. BANGLI', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5107',	(SELECT id FROM province WHERE province_code = '51'),	'KAB. KARANGASEM', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5108',	(SELECT id FROM province WHERE province_code = '51'),	'KAB. BULELENG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5171',	(SELECT id FROM province WHERE province_code = '51'),	'KOTA DENPASAR', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5201',	(SELECT id FROM province WHERE province_code = '52'),	'KAB. LOMBOK BARAT', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5202',	(SELECT id FROM province WHERE province_code = '52'),	'KAB. LOMBOK TENGAH', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5203',	(SELECT id FROM province WHERE province_code = '52'),	'KAB. LOMBOK TIMUR', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5204',	(SELECT id FROM province WHERE province_code = '52'),	'KAB. SUMBAWA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5205',	(SELECT id FROM province WHERE province_code = '52'),	'KAB. DOMPU', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5206',	(SELECT id FROM province WHERE province_code = '52'),	'KAB. BIMA', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5207',	(SELECT id FROM province WHERE province_code = '52'),	'KAB. SUMBAWA BARAT', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5208',	(SELECT id FROM province WHERE province_code = '52'),	'KAB. LOMBOK UTARA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5271',	(SELECT id FROM province WHERE province_code = '52'),	'KOTA MATARAM', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5272',	(SELECT id FROM province WHERE province_code = '52'),	'KOTA BIMA', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5301',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. KUPANG',						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5302',	(SELECT id FROM province WHERE province_code = '53'),	'KAB TIMOR TENGAH SELATAN', 		(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5303',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. TIMOR TENGAH UTARA', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5304',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. BELU', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5305',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. ALOR', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5306',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. FLORES TIMUR', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5307',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. SIKKA', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5308',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. ENDE', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5309',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. NGADA', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5310',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. MANGGARAI', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5311',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. SUMBA TIMUR', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5312',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. SUMBA BARAT', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5313',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. LEMBATA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5314',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. ROTE NDAO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5315',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. MANGGARAI BARAT', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5316',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. NAGEKEO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5317',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. SUMBA TENGAH', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5318',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. SUMBA BARAT DAYA',			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5319',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. MANGGARAI TIMUR', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5320',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. SABU RAIJUA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5321',	(SELECT id FROM province WHERE province_code = '53'),	'KAB. MALAKA', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('5371',	(SELECT id FROM province WHERE province_code = '53'),	'KOTA KUPANG', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6101',	(SELECT id FROM province WHERE province_code = '61'),	'KAB. SAMBAS', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6102',	(SELECT id FROM province WHERE province_code = '61'),	'KAB. MEMPAWAH', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6103',	(SELECT id FROM province WHERE province_code = '61'),	'KAB. SANGGAU', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6104',	(SELECT id FROM province WHERE province_code = '61'),	'KAB. KETAPANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6105',	(SELECT id FROM province WHERE province_code = '61'),	'KAB. SINTANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6106',	(SELECT id FROM province WHERE province_code = '61'),	'KAB. KAPUAS HULU', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6107',	(SELECT id FROM province WHERE province_code = '61'),	'KAB. BENGKAYANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6108',	(SELECT id FROM province WHERE province_code = '61'),	'KAB. LANDAK', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6109',	(SELECT id FROM province WHERE province_code = '61'),	'KAB. SEKADAU', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6110',	(SELECT id FROM province WHERE province_code = '61'),	'KAB. MELAWI', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6111',	(SELECT id FROM province WHERE province_code = '61'),	'KAB. KAYONG UTARA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6112',	(SELECT id FROM province WHERE province_code = '61'),	'KAB. KUBU RAYA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6171',	(SELECT id FROM province WHERE province_code = '61'),	'KOTA PONTIANAK', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6172',	(SELECT id FROM province WHERE province_code = '61'),	'KOTA SINGKAWANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6201',	(SELECT id FROM province WHERE province_code = '62'),	'KAB. KOTAWARINGIN BARAT', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6202',	(SELECT id FROM province WHERE province_code = '62'),	'KAB. KOTAWARINGIN TIMUR', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6203',	(SELECT id FROM province WHERE province_code = '62'),	'KAB. KAPUAS', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6204',	(SELECT id FROM province WHERE province_code = '62'),	'KAB. BARITO SELATAN', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6205',	(SELECT id FROM province WHERE province_code = '62'),	'KAB. BARITO UTARA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6206',	(SELECT id FROM province WHERE province_code = '62'),	'KAB. KATINGAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6207',	(SELECT id FROM province WHERE province_code = '62'),	'KAB. SERUYAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6208',	(SELECT id FROM province WHERE province_code = '62'),	'KAB. SUKAMARA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6209',	(SELECT id FROM province WHERE province_code = '62'),	'KAB. LAMANDAU', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6210',	(SELECT id FROM province WHERE province_code = '62'),	'KAB. GUNUNG MAS', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6211',	(SELECT id FROM province WHERE province_code = '62'),	'KAB. PULANG PISAU', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6212',	(SELECT id FROM province WHERE province_code = '62'),	'KAB. MURUNG RAYA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6213',	(SELECT id FROM province WHERE province_code = '62'),	'KAB. BARITO TIMUR', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6271',	(SELECT id FROM province WHERE province_code = '62'),	'KOTA PALANGKARAYA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6301',	(SELECT id FROM province WHERE province_code = '63'),	'KAB. TANAH LAUT', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6302',	(SELECT id FROM province WHERE province_code = '63'),	'KAB. KOTABARU', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6303',	(SELECT id FROM province WHERE province_code = '63'),	'KAB. BANJAR', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6304',	(SELECT id FROM province WHERE province_code = '63'),	'KAB. BARITO KUALA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6305',	(SELECT id FROM province WHERE province_code = '63'),	'KAB. TAPIN', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6306',	(SELECT id FROM province WHERE province_code = '63'),	'KAB. HULU SUNGAI SELATAN', 		(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6307',	(SELECT id FROM province WHERE province_code = '63'),	'KAB. HULU SUNGAI TENGAH', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6308',	(SELECT id FROM province WHERE province_code = '63'),	'KAB. HULU SUNGAI UTARA', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6309',	(SELECT id FROM province WHERE province_code = '63'),	'KAB. TABALONG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6310',	(SELECT id FROM province WHERE province_code = '63'),	'KAB. TANAH BUMBU', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6311',	(SELECT id FROM province WHERE province_code = '63'),	'KAB. BALANGAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6371',	(SELECT id FROM province WHERE province_code = '63'),	'KOTA BANJARMASIN', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6372',	(SELECT id FROM province WHERE province_code = '63'),	'KOTA BANJARBARU', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6401',	(SELECT id FROM province WHERE province_code = '64'),	'KAB. PASER', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6402',	(SELECT id FROM province WHERE province_code = '64'),	'KAB. KUTAI KARTANEGARA', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6403',	(SELECT id FROM province WHERE province_code = '64'),	'KAB. BERAU', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6407',	(SELECT id FROM province WHERE province_code = '64'),	'KAB. KUTAI BARAT', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6408',	(SELECT id FROM province WHERE province_code = '64'),	'KAB. KUTAI TIMUR', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6409',	(SELECT id FROM province WHERE province_code = '64'),	'KAB. PENAJAM PASER UTARA', 		(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6411',	(SELECT id FROM province WHERE province_code = '64'),	'KAB. MAHAKAM ULU', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6471',	(SELECT id FROM province WHERE province_code = '64'),	'KOTA BALIKPAPAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6472',	(SELECT id FROM province WHERE province_code = '64'),	'KOTA SAMARINDA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6474',	(SELECT id FROM province WHERE province_code = '64'),	'KOTA BONTANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6501',	(SELECT id FROM province WHERE province_code = '65'),	'KAB. BULUNGAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6502',	(SELECT id FROM province WHERE province_code = '65'),	'KAB. MALINAU', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6503',	(SELECT id FROM province WHERE province_code = '65'),	'KAB. NUNUKAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6504',	(SELECT id FROM province WHERE province_code = '65'),	'KAB. TANA TIDUNG', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('6571',	(SELECT id FROM province WHERE province_code = '65'),	'KOTA TARAKAN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7101',	(SELECT id FROM province WHERE province_code = '71'),	'KAB. BOLAANG MONGONDOW', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7102',	(SELECT id FROM province WHERE province_code = '71'),	'KAB. MINAHASA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7103',	(SELECT id FROM province WHERE province_code = '71'),	'KAB. KEPULAUAN SANGIHE', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7104',	(SELECT id FROM province WHERE province_code = '71'),	'KAB. KEPULAUAN TALAUD', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7105',	(SELECT id FROM province WHERE province_code = '71'),	'KAB. MINAHASA SELATAN', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7106',	(SELECT id FROM province WHERE province_code = '71'),	'KAB. MINAHASA UTARA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7107',	(SELECT id FROM province WHERE province_code = '71'),	'KAB. MINAHASA TENGGARA', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7108',	(SELECT id FROM province WHERE province_code = '71'),	'KAB. BOLAANG MONGONDOW UTARA', 	(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7109',	(SELECT id FROM province WHERE province_code = '71'),	'KAB. KEP. SIAU TAGULANDANG BIARO', (SELECT id FROM users WHERE email = 'admin@mail.com')),
('7110',	(SELECT id FROM province WHERE province_code = '71'),	'KAB. BOLAANG MONGONDOW TIMUR', 	(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7111',	(SELECT id FROM province WHERE province_code = '71'),	'KAB. BOLAANG MONGONDOW SELATAN', 	(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7171',	(SELECT id FROM province WHERE province_code = '71'),	'KOTA MANADO', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7172',	(SELECT id FROM province WHERE province_code = '71'),	'KOTA BITUNG', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7173',	(SELECT id FROM province WHERE province_code = '71'),	'KOTA TOMOHON', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7174',	(SELECT id FROM province WHERE province_code = '71'),	'KOTA KOTAMOBAGU', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7201',	(SELECT id FROM province WHERE province_code = '72'),	'KAB. BANGGAI', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7202',	(SELECT id FROM province WHERE province_code = '72'),	'KAB. POSO', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7203',	(SELECT id FROM province WHERE province_code = '72'),	'KAB. DONGGALA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7204',	(SELECT id FROM province WHERE province_code = '72'),	'KAB. TOLI TOLI', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7205',	(SELECT id FROM province WHERE province_code = '72'),	'KAB. BUOL', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7206',	(SELECT id FROM province WHERE province_code = '72'),	'KAB. MOROWALI', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7207',	(SELECT id FROM province WHERE province_code = '72'),	'KAB. BANGGAI KEPULAUAN', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7208',	(SELECT id FROM province WHERE province_code = '72'),	'KAB. PARIGI MOUTONG', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7209',	(SELECT id FROM province WHERE province_code = '72'),	'KAB. TOJO UNA UNA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7210',	(SELECT id FROM province WHERE province_code = '72'),	'KAB. SIGI',	 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7211',	(SELECT id FROM province WHERE province_code = '72'),	'KAB. BANGGAI LAUT', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7212',	(SELECT id FROM province WHERE province_code = '72'),	'KAB. MOROWALI UTARA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7271',	(SELECT id FROM province WHERE province_code = '72'),	'KOTA PALU', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7301',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. KEPULAUAN SELAYAR', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7302',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. BULUKUMBA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7303',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. BANTAENG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7304',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. JENEPONTO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7305',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. TAKALAR', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7306',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. GOWA', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7307',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. SINJAI', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7308',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. BONE', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7309',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. MAROS', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7310',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. PANGKAJENE KEPULAUAN', 		(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7311',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. BARRU', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7312',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. SOPPENG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7313',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. WAJO', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7314',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. SIDENRENG RAPPANG', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7315',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. PINRANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7316',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. ENREKANG', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7317',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. LUWU', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7318',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. TANA TORAJA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7322',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. LUWU UTARA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7324',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. LUWU TIMUR', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7326',	(SELECT id FROM province WHERE province_code = '73'),	'KAB. TORAJA UTARA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7371',	(SELECT id FROM province WHERE province_code = '73'),	'KOTA MAKASSAR', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7372',	(SELECT id FROM province WHERE province_code = '73'),	'KOTA PARE PARE', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7373',	(SELECT id FROM province WHERE province_code = '73'),	'KOTA PALOPO', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7401',	(SELECT id FROM province WHERE province_code = '74'),	'KAB. KOLAKA', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7402',	(SELECT id FROM province WHERE province_code = '74'),	'KAB. KONAWE', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7403',	(SELECT id FROM province WHERE province_code = '74'),	'KAB. MUNA', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7404',	(SELECT id FROM province WHERE province_code = '74'),	'KAB. BUTON', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7405',	(SELECT id FROM province WHERE province_code = '74'),	'KAB. KONAWE SELATAN', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7406',	(SELECT id FROM province WHERE province_code = '74'),	'KAB. BOMBANA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7407',	(SELECT id FROM province WHERE province_code = '74'),	'KAB. WAKATOBI', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7408',	(SELECT id FROM province WHERE province_code = '74'),	'KAB. KOLAKA UTARA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7409',	(SELECT id FROM province WHERE province_code = '74'),	'KAB. KONAWE UTARA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7410',	(SELECT id FROM province WHERE province_code = '74'),	'KAB. BUTON UTARA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7411',	(SELECT id FROM province WHERE province_code = '74'),	'KAB. KOLAKA TIMUR', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7412',	(SELECT id FROM province WHERE province_code = '74'),	'KAB. KONAWE KEPULAUAN', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7413',	(SELECT id FROM province WHERE province_code = '74'),	'KAB. MUNA BARAT', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7414',	(SELECT id FROM province WHERE province_code = '74'),	'KAB. BUTON TENGAH', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7415',	(SELECT id FROM province WHERE province_code = '74'),	'KAB. BUTON SELATAN', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7471',	(SELECT id FROM province WHERE province_code = '74'),	'KOTA KENDARI', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7472',	(SELECT id FROM province WHERE province_code = '74'),	'KOTA BAU BAU', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7501',	(SELECT id FROM province WHERE province_code = '75'),	'KAB. GORONTALO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7502',	(SELECT id FROM province WHERE province_code = '75'),	'KAB. BOALEMO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7503',	(SELECT id FROM province WHERE province_code = '75'),	'KAB. BONE BOLANGO', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7504',	(SELECT id FROM province WHERE province_code = '75'),	'KAB. PAHUWATO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7505',	(SELECT id FROM province WHERE province_code = '75'),	'KAB. GORONTALO UTARA', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7571',	(SELECT id FROM province WHERE province_code = '75'),	'KOTA GORONTALO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7601',	(SELECT id FROM province WHERE province_code = '76'),	'KAB. PASANGKAYU', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7602',	(SELECT id FROM province WHERE province_code = '76'),	'KAB. MAMUJU', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7603',	(SELECT id FROM province WHERE province_code = '76'),	'KAB. MAMASA', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7604',	(SELECT id FROM province WHERE province_code = '76'),	'KAB. POLEWALI MANDAR', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7605',	(SELECT id FROM province WHERE province_code = '76'),	'KAB. MAJENE', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('7606',	(SELECT id FROM province WHERE province_code = '76'),	'KAB. MAMUJU TENGAH', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8101',	(SELECT id FROM province WHERE province_code = '81'),	'KAB. MALUKU TENGAH', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8102',	(SELECT id FROM province WHERE province_code = '81'),	'KAB. MALUKU TENGGARA', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8103',	(SELECT id FROM province WHERE province_code = '81'),	'KAB. KEPULAUAN TANIMBAR', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8104',	(SELECT id FROM province WHERE province_code = '81'),	'KAB. BURU', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8105',	(SELECT id FROM province WHERE province_code = '81'),	'KAB. SERAM BAGIAN TIMUR', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8106',	(SELECT id FROM province WHERE province_code = '81'),	'KAB. SERAM BAGIAN BARAT', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8107',	(SELECT id FROM province WHERE province_code = '81'),	'KAB. KEPULAUAN ARU', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8108',	(SELECT id FROM province WHERE province_code = '81'),	'KAB. MALUKU BARAT DAYA', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8109',	(SELECT id FROM province WHERE province_code = '81'),	'KAB. BURU SELATAN', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8171',	(SELECT id FROM province WHERE province_code = '81'),	'KOTA AMBON', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8172',	(SELECT id FROM province WHERE province_code = '81'),	'KOTA TUAL', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8201',	(SELECT id FROM province WHERE province_code = '82'),	'KAB. HALMAHERA BARAT', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8202',	(SELECT id FROM province WHERE province_code = '82'),	'KAB. HALMAHERA TENGAH', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8203',	(SELECT id FROM province WHERE province_code = '82'),	'KAB. HALMAHERA UTARA', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8204',	(SELECT id FROM province WHERE province_code = '82'),	'KAB. HALMAHERA SELATAN', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8205',	(SELECT id FROM province WHERE province_code = '82'),	'KAB. KEPULAUAN SULA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8206',	(SELECT id FROM province WHERE province_code = '82'),	'KAB. HALMAHERA TIMUR', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8207',	(SELECT id FROM province WHERE province_code = '82'),	'KAB. PULAU MOROTAI', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8208',	(SELECT id FROM province WHERE province_code = '82'),	'KAB. PULAU TALIABU', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8271',	(SELECT id FROM province WHERE province_code = '82'),	'KOTA TERNATE', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('8272',	(SELECT id FROM province WHERE province_code = '82'),	'KOTA TIDORE KEPULAUAN', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9101',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. MERAUKE', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9102',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. JAYAWIJAYA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9103',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. JAYAPURA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9104',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. NABIRE', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9105',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. KEPULAUAN YAPEN', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9106',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. BIAK NUMFOR', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9107',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. PUNCAK JAYA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9108',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. PANIAI', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9109',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. MIMIKA', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9110',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. SARMI',						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9111',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. KEEROM', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9112',	(SELECT id FROM province WHERE province_code = '91'),	'KAB PEGUNUNGAN BINTANG', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9113',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. YAHUKIMO', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9114',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. TOLIKARA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9115',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. WAROPEN', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9116',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. BOVEN DIGOEL', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9117',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. MAPPI', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9118',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. ASMAT', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9119',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. SUPIORI', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9120',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. MAMBERAMO RAYA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9121',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. MAMBERAMO TENGAH', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9122',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. YALIMO',						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9123',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. LANNY JAYA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9124',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. NDUGA', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9125',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. PUNCAK', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9126',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. DOGIYAI', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9127',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. INTAN JAYA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9128',	(SELECT id FROM province WHERE province_code = '91'),	'KAB. DEIYAI', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9171',	(SELECT id FROM province WHERE province_code = '91'),	'KOTA JAYAPURA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9201',	(SELECT id FROM province WHERE province_code = '92'),	'KAB. SORONG', 						(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9202',	(SELECT id FROM province WHERE province_code = '92'),	'KAB. MANOKWARI', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9203',	(SELECT id FROM province WHERE province_code = '92'),	'KAB. FAK FAK', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9204',	(SELECT id FROM province WHERE province_code = '92'),	'KAB. SORONG SELATAN', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9205',	(SELECT id FROM province WHERE province_code = '92'),	'KAB. RAJA AMPAT', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9206',	(SELECT id FROM province WHERE province_code = '92'),	'KAB. TELUK BINTUNI', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9207',	(SELECT id FROM province WHERE province_code = '92'),	'KAB. TELUK WONDAMA', 				(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9208',	(SELECT id FROM province WHERE province_code = '92'),	'KAB. KAIMANA', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9209',	(SELECT id FROM province WHERE province_code = '92'),	'KAB. TAMBRAUW', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9210',	(SELECT id FROM province WHERE province_code = '92'),	'KAB. MAYBRAT', 					(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9211',	(SELECT id FROM province WHERE province_code = '92'),	'KAB. MANOKWARI SELATAN', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9212',	(SELECT id FROM province WHERE province_code = '92'),	'KAB. PEGUNUNGAN ARFAK', 			(SELECT id FROM users WHERE email = 'admin@mail.com')),
('9271',	(SELECT id FROM province WHERE province_code = '92'),	'KOTA SORONG', 						(SELECT id FROM users WHERE email = 'admin@mail.com'));

INSERT INTO category (category_code, category_name, created_by) VALUES 
	('CAT01', 'HR Administration', (SELECT id FROM users WHERE email = 'admin@mail.com')),
	('CAT02', 'Planning & Recruitment', (SELECT id FROM users WHERE email = 'admin@mail.com'));



